### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = mako &
exec-once = nm-applet &
exec-once = elephant &
exec-once = ~/.dotfiles/scripts/hyprland/windows-symlink.sh
exec-once = ~/.dotfiles/scripts/hyprland/wallpaper.sh
exec-once = lxqt-policykit-agent &
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_RUNTIME_DIR
exec-once = waybar &
exec-once = [workspace 1 silent] wezterm -e tmux new -spadrao
exec-once = [workspace 2] zen-browser
exec-once = [workspace 3 silent] vesktop
exec-once = [workspace 4 silent] spotify
exec-once = [workspace 5 silent] obs --scene "Padrao" --startreplaybuffer




